services:
  - type: web
    name: alexandria-hostels
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn alexandria_hostels.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: alexandria_hostels.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: alexandria-db
          property: connectionString
    plan: free

databases:
  - name: alexandria-db
    plan: free